### ISSUE TITLE
Clamav socket

### ISSUE THREAD

**Issue by teoberi** [Securepoint/squid-ecap-av#1]
According to the configuration file  [clamav/etc/clamd.conf.sample](https://github.com/Cisco-Talos/clamav/blob/09f373f82ad0978e267cc9b795aa93d7f8e8b7d2/etc/clamd.conf.sample#L96) the local socket file is **clamd.socket** but in the configuration file [squid-ecap-av/src/ecap_adapter_av.conf](https://github.com/Securepoint/squid-ecap-av/blob/6293337d029f0bc8a261d0dbfec338f6f47f19fa/src/ecap_adapter_av.conf#L5) it appears avdsocket = /tmp/clamd.sock
To avoid changing the configuration file, it would be necessary to update **avdsocket = /tmp/clamd.sock** -> **avdsocket = /tmp/clamd.socket**
Are there any issues preventing this update?

**Comment by sp-andwei** [comment]
Seems reasonable.

**Comment by teoberi** [comment]
Sorry for that!
It seems that the latest version of Clamav 1.2.0 remodifies the socket name and location for (clamd.socket -> clamd.sock) to reflect the recommended in Docker images.
https://github.com/Cisco-Talos/clamav/releases/tag/clamav-1.2.0

> Other improvements
> ...
> The suggested path for the clamd.pid and clamd.sock file in the sample
> configs have been updated to reflect the recommended locations for these files
> in the Docker images. These are:
> 
> /run/clamav/clamd.pid
> /run/clamav/clamd.sock
> For consistency, it now specifies clamd.sock instead of clamd.socket
> 
> Patch courtesy of computersalat.
> 
> GitHub pull request: https://github.com/Cisco-Talos/clamav/pull/931
