### ISSUE TITLE
Squid-ecap-av compilation question

### ISSUE THREAD

**Issue by teoberi** [Securepoint/squid-ecap-av#2]
Is there a particular reason for avoiding compiling with c++11?
[Line 5](https://github.com/Securepoint/squid-ecap-av/blob/6293337d029f0bc8a261d0dbfec338f6f47f19fa/CMakeLists.txt#L5) file squid-ecap-av/CMakeLists.txt

**Comment by sp-andwei** [comment]
There used to be one, but not anymore.
