### ISSUE TITLE
Ikarus scan.server sock permision

### ISSUE THREAD

**Issue by teoberi** [Securepoint/squid-ecap-av#3]
I'm testing Ikarus scanserver-6.1.6l64 with the latest changes to Securepoint/squid-ecap-av and I have a problem with permissions for ikarus.sock
`ls -l /tmp/`

> srw-rw-rw- 1 xxx xxx    0 Mar  3 12:14 clamd.socket
> srwxr-xr-x 1 xxx xxx    0 Mar  3 13:34 ikarus.sock

I have already modified ecap_adapter_av.conf
`avdsocket = /tmp/ikarus.sock`

If I configure the proxy in browser and try to access a web page, this message appears:
> Internal error!
> While scanning your request for virus infection an internal error occured!
> can't initialize AV-daemon socket: Bad file descriptor.

If I change the permissions for ikarus.sock to those of clamd.sock, with command:
`chmod 666 /tmp/ikarus.sock`

everything is OK

**Comment by sp-andwei** [comment]
Hey. Not much we can do about that from within the ecap-Adapter. There should soon be an option to configure the permissions of the socket using the scanserver configuration. 

Other than that, you will have to make sure that whatever user squid runs as obviously needs write access to the socket (under Linux at least).

**Comment by teoberi** [comment]
Fair.
Thank you.
